name: blog_mockup
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/article_image.jpg
    - assets/images/profile_pic.png

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Black.otf
          weight: 600
        - asset: assets/fonts/Gotham-Medium.otf
          weight: 400
    - family: Caecilia
      fonts:
        - asset: assets/fonts/CaeciliaLTStd-Roman.otf
          weight: 400